### ISSUE TITLE
Implement documentation on the PhysicsObjectExtractor

### ISSUE THREAD

**Issue by caredg** [cernopendata/cms-opendata-guide#18]
See #7. Describe the basic principles on how to get information from physics objects.

**Comment by katilp** [comment]
Restructure Physics objects part for a better information flow.
Add links to POET and make sure that the reader knows in which part the code snippets are supposed to go.

**Comment by katilp** [comment]
This could be closed and updates and improvements can be followed up in separate issues. @caredg ?

**Comment by caredg** [comment]
AGree, closing...
