### ISSUE TITLE
Create and complete instructions for CMSSW

### ISSUE THREAD

**Issue by caredg** [cernopendata/cms-opendata-guide#22]
Following #6, work on the instructions for CMSSW.

**Comment by caredg** [comment]
@topaklihuseyin thanks a lot [for this first draft](https://github.com/topaklihuseyin/CMSSW).  Looks good to me so far.  I think this goes along with the idea with have as of now.... Of course things will certainly evolve, but we can make additions, corrections as we go along.

A couple things that I thought:

- [ ] Maybe it would be good to remove the sentence "Unlike the previous event processing frameworks" (I suppose that does not mean much to external people or even younger CMS folks who didn't have to struggle with ORCA and OSCAR like some of us)
- [ ] We have to make sure that we show explicitly (I think this is important) the simple steps to create an EDAnalyzer (or point to the right place according to #6).
- [ ] One key aspect of configuration that I would appreciate, as an external person (maybe because I am thinking like a student), is to be able to realize that, for instance in a given configuration file, a python module like this one (random example)

`process.hltPFJetsMatchedToCaloJets320Regional = cms.EDProducer( "PFJetsMatchedToFilteredCaloJetsProducer",
  DeltaR = cms.double( 0.5 ),
  CaloJetFilter = cms.InputTag( "hltSingleJet320Regional" ),
  TriggerType = cms.int32( 85 ),
  PFJetSrc = cms.InputTag( "hltAntiKT5PFJets" )
)`

means that `PFJetsMatchedToFilteredCaloJetsProducer` is the mother code that is being configured and that it could be readily searched for in the cmssw githug repo, matching the corresponding or closest branch, in agreement with the data that is being used.  For 2011, it would be the CMSS_5_3_X [version of it](https://github.com/cms-sw/cmssw/blob/CMSSW_5_3_X/HLTrigger/JetMET/interface/PFJetsMatchedToFilteredCaloJetsProducer.h)

Finally, if you could test this locally, cloning the repo directly, that would be great.  If not, do not hesistate to push or PR to the repo, In these few days will be evolving very rapidly so it does no really matter if we make several modifications directly.
Thanks!

**Comment by topaklihuseyin** [comment]
Hİ Edgar, i removed the sentence  "Unlike the previous event processing frameworks" and wrote an EDAnalyzer  from an example. I will try push to the repo.

**Comment by topaklihuseyin** [comment]
Hi Edgar, i wrote an EDAnalyzer example from the workbook. I am not sure can i add how to add a histogram in a code? Another issue is Conditions Data, is that means what is raw, reco, digi, AOD something like this or completely different things? What do you think?

**Comment by caredg** [comment]
Hi @topaklihuseyin.  Great thanks!  
Regarding your first question, do you mean adding histo image in the instructions?  If that is the case, if you look at main [reana doc](http://docs.reana.io/) page as an expamle (we use the same mkdocs), they insert the image in [this line](https://github.com/reanahub/docs.reana.io/blame/master/docs/index.md#L7), which points to one of the images stored in their ["images"](https://github.com/reanahub/docs.reana.io/tree/master/docs/images) directory under docs.  We should create one if there is none.  Is this what you meant?
Regarding the Conditions Data, it refers to the "Global tags", so the corresponding historic version in [here](https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideFrontierConditions)

**Comment by caredg** [comment]
Just in case, [this](https://www.markdownguide.org/tools/mkdocs/) is a good reference to have in hand for formatting.

**Comment by caredg** [comment]
Sorry @topaklihuseyin, if you, on the other hand, meant adding a histogram fo the EDAnalyzer, [this](https://github.com/cms-legacydata-analyses/PhysObjectExtractorTool/blob/master/PhysObjectExtractor/src/PhysicsObjectsInfo.cc) example could help.

**Comment by topaklihuseyin** [comment]
Hi Edgar, in EDAnalyzer which i wrote is a very simple and when you run the script it's just counting the tracks and there is no histos in the output file. According the workbook next step is adding histos to script (DemoAnalyzer.cc). I was wondering can i write how to add histos to script or giving the link? 
Conditions Data side is clear now.
Thanks a lot.

**Comment by caredg** [comment]
> Hi Edgar, in EDAnalyzer which i wrote is a very simple and when you run the script it's just counting the tracks and there is no histos in the output file. According the workbook next step is adding histos to script (DemoAnalyzer.cc). I was wondering can i write how to add histos to script or giving the link?
> Conditions Data side is clear now.
> Thanks a lot.

Hi @topaklihuseyin. Thanks.  Ok, so I suppose you could actually show how to write just a histogram and output it to a file in the simplest manner possible.  I think that would be fine.

**Comment by caredg** [comment]
Hi @topaklihuseyin.  I was checking a bit your draft.  I think you should try to upload it to the guide so you can see how it looks (if you can look at ir locally, even better).  One thing I noticed is that you have references to lxplus.  There are also instances of cmssw >7X, which is not used for the moment for open data.  So that has to go because for open data users do not necessarily have access to this resources or releases.  We actually ship cmssw images for virtual machines, for which instructions are already [in place](https://cms-opendata-guide.web.cern.ch/tools/virtualmachines/) or [docker containers](http://opendata.cern.ch/docs/cms-guide-docker).  Remember that we have only released 2010 and 2011/2010 data.  

Also note that in the virtual machine guide, we do not repeat everything that is either in the twiki page or in the cern open portal site.  For instance, for the conditions data section, you could use the already availabe info in the cern open portal (see #6) and the twiki page on Frontier conditions I mentioned above.

For example when you use this twiki https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookWriteFrameworkModule, you have to align with the latest version used in cms open data, which is [CMSSW_5_3_32](http://opendata.cern.ch/docs/cms-getting-started-2011) (actually, this page, which was mentioned in #6, has a lot of stuff that can be used to explain some of the CMSSW-related things.  It is just that the information is so scattered that we need this guide to put everything together, but not necessarily copy and repeat everything).  The right revision to use might be [this one](https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookConfigFileIntro?rev=30).  I do not know.  You can check, for every twiki page, by scrolling all the way down and clicking on History.  That way we can make everything consistent with open data.

Notice that in the [virtual machines instructions](https://cms-opendata-guide.web.cern.ch/tools/virtualmachines/) I do not overpopulate the page, but try to guide the user to use what is already written and available so it makes sense for her. For this, pointing to pages and using anchors could save a lot of space and avoid to have instrucitons that are too long.

Sorry I write late about this, but I am a bit overwhelmed with the workshop and all.
Thanks!

**Comment by topaklihuseyin** [comment]
Hi Edgar, while i was writing the CMSSW   i followed the  CMSPublic twiki page and it is not related to Cern VM's.  I will uptade the draft according to your points.  For Conditions data, i created new repository and wrote new draft. If you have a time could you look at  https://github.com/topaklihuseyin/Conditions-Data and write to me comments. 

Best,

**Comment by caredg** [comment]
Hi @topaklihuseyin, thanks! Yes I know, and this kind of disconnection with what the CMS twikis have and what we need for cms open data is what makes writing this guide a bit challenging. I totally agree.  Note that Cern VM's are only a way for us to preserve the 5_3_32 (for 2011) or 4_2_8 (for 2010)
I looked at the Conditions data and it looks ok.  But actually there is no need to copy verbatim everything that is already in the portal.  You could just give a brief intro (like you already do), explain what they will find in the open portal page and direct them to it.  It does have to be clear the separation between releases, and data and MC, but that could be explained in a very simple fashion before sending them to the portal... 
In [this page](https://cms-opendata-guide.web.cern.ch/analysis/selection/objects/) that I haven't finished yet, I just guide the user to the appropriate information.  Note that I do copy evey single bit of what is in the portal documents (that would too repetitive and very hard to maintain in the future).  I guess this is more or less the idea of the guide.  Thanks a lot again!

**Comment by caredg** [comment]
BTW, I have written the home page of the guide.  That summarizes the philosophy: https://cms-opendata-guide.web.cern.ch/

**Comment by topaklihuseyin** [comment]
Hi Edgar, you summarized the philosphy very well. I updated the draft according to CMSSW checklist #6 and if you have a time could you look at https://github.com/topaklihuseyin/CMSSW and comments? I will add 5_3_32 explanations under the Cern VM?

Thanks a lot.

**Comment by caredg** [comment]
Hi @topaklihuseyin thanks! I will review it more carefully, but from a quick view, spelling out the conditions data (i.e. the details of the database snapshots and such) is probably too much.  You could also simply reference them.  Note that there will be sections for Docker and VM under Computing tools, so that should be taken into account.

**Comment by topaklihuseyin** [comment]
Hi Edgar, i just gave a link for data and monte carlo data end of the section and i also deleted VM and Docker part. 

Thanks,

**Comment by katilp** [comment]
Following up from here, for the sake of consistency, I'll add some links to the examples that we are going to refer to (POET and AOD2NanoAODOutreachTool for Run1 data).
