### ISSUE TITLE
Create and complete instructions on Docker containers

### ISSUE THREAD

**Issue by caredg** [cernopendata/cms-opendata-guide#27]
Complete these instrucitons according to #4.

**Comment by caredg** [comment]
Maybe see: https://cms-opendata-guide.web.cern.ch/tools/virtualmachines/

**Comment by katilp** [comment]
@caredg can this be closed or do we need more in https://cms-opendata-guide.web.cern.ch/tools/docker/ ?

**Comment by caredg** [comment]
I think it is ok to close it.
