### ISSUE TITLE
Updating and integration issues (slowness) at push

### ISSUE THREAD

**Issue by caredg** [cernopendata/cms-opendata-guide#28]
Hi @tiborsimko and @mvidalgarcia, I am not sure what is going on, but every time one pushes to the repository to update the site, the travis integration fails as there is no rule for 'make html' (no makefile) and it seems that nothing gets updated (this seems to have been the case since the very initial move to mkdocs).  However, in the past, I have noticed that after a while, the modifications ARE propagated.  This is troublesome right now because the delay is considerable and we are sort of running against time to populate these documentation and need to see the site (I can build it and see it locally, but still).  I can't completely figure out how the modifications are propagated to openshift.  It is probably through webhooks, but I might be just dead wrong.  I'd love to play around, but I do not want to mess up anything. Could you please take a look? Thanks!

**Comment by tiborsimko** [comment]
Hi @caredg, the Travis CI configuration was created for ReadTheDocs, and wasn't updated afterwards. The CI run fails quickly, looking at [build history](https://travis-ci.org/github/cernopendata/cms-opendata-guide/builds), it typically takes around 30 seconds to run. So it should not be slowing down things too much? Looking further in the deployment chain, looking at [CERN OpenShift builds](https://openshift.cern.ch/console/project/cms-opendata-guide/browse/builds/cms-opendata-guide?tab=history), they typically take 35 seconds. Again not too much?  Have you seen more considerable delays than a few minutes after pushing a commit?

That said, we should amend the Travis CI recipe to better fit the mkdocs style... I can take care of that.

**Comment by tiborsimko** [comment]
Hi @caredg, I made a PR to have proper CI tester, including Markdown linter, link checker, and site builder. (Using the same rules as in our [docs.reana.io](http://docs.reana.io/).) Note that it was necessary to clean existing Markdown pages regarding whitespace, indentation, or section levels; I have done that as well as part of PR #29.

**Comment by caredg** [comment]
closed by #29

**Comment by caredg** [comment]
> Hi @caredg, the Travis CI configuration was created for ReadTheDocs, and wasn't updated afterwards. The CI run fails quickly, looking at [build history](https://travis-ci.org/github/cernopendata/cms-opendata-guide/builds), it typically takes around 30 seconds to run. So it should not be slowing down things too much? Looking further in the deployment chain, looking at [CERN OpenShift builds](https://openshift.cern.ch/console/project/cms-opendata-guide/browse/builds/cms-opendata-guide?tab=history), they typically take 35 seconds. Again not too much? Have you seen more considerable delays than a few minutes after pushing a commit?
> 
> That said, we should amend the Travis CI recipe to better fit the mkdocs style... I can take care of that.

Sorry to comment after closing, but I just saw this.  Right, after testing again, I realized that it was my chrome browser cache that needed to be removed for the page to update correctly.  I thought I tested this with another browser with similar results, but who knows, maybe that cache was also polluted. Somehow I was tricked by the previously failing travis, I though it might have to do with it.  Thanks a lot for checking and cleaning up.
