### ISSUE TITLE
Add a disclaimer

### ISSUE THREAD

**Issue by katilp** [cernopendata/cms-opendata-guide#38]
Remove "official" in the welcome sentence "Welcome to the official guide for CMS open data".

Add a disclaimer inline with https://www.gnu.org/licenses/gpl-3.0.en.html or else to make it clear that this guide is provided by the CMS open data group, at best-effort basis. 

Maybe:

Welcome to the CMS open data guide.

This guide is brought to you by the CMS open data group, on a best-effort basis. All software and instructions are provided "as is", without warranty of any kind. This is ongoing work and we appreciate your feedback and/or your help building this guide

@caredg your thoughts?

**Comment by caredg** [comment]
sounds good
