### ISSUE TITLE
cms-opendata-guide live site not updating (in openshift?)

### ISSUE THREAD

**Issue by caredg** [cernopendata/cms-opendata-guide#50]
@mvidalgarcia @tiborsimko I think the live site is not updating any longer.  It seems that at the Github level everything builds ok, but somehow openshift isn't getting those updates.  Could it be that the webhooks changed after the openshift upgrade?  I do not think I can check anything about the configuration of this site on openshift so I can't investigate further.  Could you please help us? Thanks a lot.

**Comment by mvidalgarcia** [comment]
Looks like this might be the culprit https://github.com/cernopendata/cms-opendata-guide/commit/79a8253227614e48101fff08df84e2387eee5f19, maybe you're using a different version locally and that feature isn't available? [I guess it's always installing the latest version](https://github.com/cernopendata/cms-opendata-guide/blob/6614f4184db0c229c3a42697dc0e31861b4f1c76/requirements.txt#L1) of mkdocs as the requirement is not upper pinned.

**Comment by caredg** [comment]
Thanks @mvidalgarcia for debugging this!  I or @jieunyoo will check.

**Comment by jieunyoo** [comment]
I updated the versions in mkdocs and mkdocs-material, and this resolved the issue. Thank you! @mvidalgarcia @caredg
